### ISSUE TITLE
The coordinate system in PlastinceLab

### ISSUE THREAD

**Issue by EE-LiuYunhao** [hzaskywalker/PlasticineLab#11]
When I tried to applied the agent trained in the PlasticineLab to real robots, or used a third-party CG tool to handle the rendering result, I found the coordinate system in the PlasticineLab was different from the right-hand Z-up system that are commonly used in the `Open3D`, `PyTorch3D` or `Blender`. Could you please indicate what coordinate system is utilized in the PlasticineLab?

**Comment by DONGXUDUAN** [comment]
Its x,y,z correspond to y,z,x in right-hand  Z-up system.

**Comment by EE-LiuYunhao** [comment]
Thank you for the explanation.
