### ISSUE TITLE
How can I get depth image？

### ISSUE THREAD

**Issue by DONGXUDUAN** [hzaskywalker/PlasticineLab#12]
Excuse me, how can I get depth image, I mean is there any fuction that I can use directly?

**Comment by hzaskywalker** [comment]
Thanks for your interests in PlasticineLab. Sorry that I am not monitoring the issues in this repo. Could you please send me your email? I can share you the rendering code and guide you to set up the depth renderer in PlasticineLab.

**Comment by DONGXUDUAN** [comment]
Thank you so much, here is my email: ddx21@mails.tsinghua.edu.cn

**Comment by Skylark0924** [comment]
> Thanks for your interests in PlasticineLab. Sorry that I am not monitoring the issues in this repo. Could you please send me your email? I can share you the rendering code and guide you to set up the depth renderer in PlasticineLab.

Hi, thanks for your excellent simulator. Could you share with me the same guidance?  My email: jjliu@mae.cuhk.edu.hk Thanks a lot!
