### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by WenqiangX** [hzaskywalker/PlasticineLab#2]
Hey guys, I am wondering how to use this framework to visualize the sequence as is shown on your website. I tried to use `engine/renderer/test.py`, but it can only display one frame. Would you please help me with that? Thanks a lot :)

**Comment by hzaskywalker** [comment]
It is simply an open gym environment, so you can always render each frame by "env.render()". See [](https://github.com/hzaskywalker/PlasticineLab/blob/ac1a2f7b0bbbe88706b51bf3aa9d72483e1d05b6/plb/optimizer/solver.py#L100) as an example. Here I render the rgb images and save them into a folder for visualization.
